name: Create WP plugin ZIP on release

on:
  release:
    types: [published]

jobs:
  build-and-upload-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          PLUGIN_SLUG=${{ github.event.repository.name }}
          ZIP_NAME="${PLUGIN_SLUG}-${{ github.event.release.tag_name }}.zip"
          echo "PLUGIN_SLUG=$PLUGIN_SLUG" >> $GITHUB_ENV
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV
          echo "ZIP_PATH=${GITHUB_WORKSPACE}/${ZIP_NAME}" >> $GITHUB_ENV

      - name: build dependencies
        run: |
          if [ -f package.json ]; then
            npm ci
            npm run build || true
          fi
          if [ -f composer.json ]; then
            composer install --no-dev --no-interaction || true
          fi

      - name: Prepare build directory
        run: |
          mkdir -p build/${{ env.PLUGIN_SLUG }}
          rsync -av --exclude="build" --exclude=".git*" --exclude="node_modules" \
                   --exclude=".github" --exclude="tests" --exclude="*.zip" ./ build/${{ env.PLUGIN_SLUG }}/

      - name: Create ZIP
        working-directory: build
        run: |
          zip -r "${{ env.ZIP_NAME }}" "${{ env.PLUGIN_SLUG }}"
          mv "${{ env.ZIP_NAME }}" ../
          ls -lh ../

      - name: Verify ZIP exists
        run: |
          echo "✅ Checking ZIP:"
          ls -lh "${{ env.ZIP_NAME }}" || (echo "❌ ZIP not found!" && exit 1)

      - name: Upload ZIP to release
        env:
          ZIP_PATH: ${{ env.ZIP_PATH }}
        run: |
          echo "Uploading $ZIP_PATH"
          gh release upload "${{ github.event.release.tag_name }}" "$ZIP_PATH" --clobber
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
