name: Build WP Plugin ZIP on Release

on:
  release:
    types: [published]

permissions:
  contents: read

env:
  PLUGIN_SLUG: go-organic-wp-plugin

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up variables
        id: vars
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          ZIP_NAME="release.zip"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV
          echo "ZIP_PATH=$PWD/$ZIP_NAME" >> $GITHUB_ENV

      - name: Create plugin ZIP
        run: |
          mkdir -p build
          zip -r "$ZIP_NAME" . -x ".git*" -x ".github*" -x "node_modules/*"
          mv "$ZIP_NAME" build/

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Upload ZIP to Release (using PAT)
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        run: |
          gh release upload "${TAG_NAME}" "build/${ZIP_NAME}" --clobber
